export const supportedLanguages = [
  ["Afrikaans", ["af-ZA"]],
  ["አማርኛ", ["am-ET"]],
  ["Azərbaycanca", ["az-AZ"]],
  ["বাংলা", ["bn-BD", "বাংলাদেশ"], ["bn-IN", "ভারত"]],
  ["Bahasa Indonesia", ["id-ID"]],
  ["Bahasa Melayu", ["ms-MY"]],
  ["Català", ["ca-ES"]],
  ["Čeština", ["cs-CZ"]],
  ["Dansk", ["da-DK"]],
  ["Deutsch", ["de-DE"]],
  [
    "English",
    ["en-AU", "Australia"],
    ["en-CA", "Canada"],
    ["en-IN", "India"],
    ["en-KE", "Kenya"],
    ["en-TZ", "Tanzania"],
    ["en-GH", "Ghana"],
    ["en-NZ", "New Zealand"],
    ["en-NG", "Nigeria"],
    ["en-ZA", "South Africa"],
    ["en-PH", "Philippines"],
    ["en-GB", "United Kingdom"],
    ["en-US", "United States"],
  ],
  [
    "Español",
    ["es-AR", "Argentina"],
    ["es-BO", "Bolivia"],
    ["es-CL", "Chile"],
    ["es-CO", "Colombia"],
    ["es-CR", "Costa Rica"],
    ["es-EC", "Ecuador"],
    ["es-SV", "El Salvador"],
    ["es-ES", "España"],
    ["es-US", "Estados Unidos"],
    ["es-GT", "Guatemala"],
    ["es-HN", "Honduras"],
    ["es-MX", "México"],
    ["es-NI", "Nicaragua"],
    ["es-PA", "Panamá"],
    ["es-PY", "Paraguay"],
    ["es-PE", "Perú"],
    ["es-PR", "Puerto Rico"],
    ["es-DO", "República Dominicana"],
    ["es-UY", "Uruguay"],
    ["es-VE", "Venezuela"],
  ],
  ["Euskara", ["eu-ES"]],
  ["Filipino", ["fil-PH"]],
  ["Français", ["fr-FR"]],
  ["Basa Jawa", ["jv-ID"]],
  ["Galego", ["gl-ES"]],
  ["ગુજરાતી", ["gu-IN"]],
  ["Hrvatski", ["hr-HR"]],
  ["IsiZulu", ["zu-ZA"]],
  ["Íslenska", ["is-IS"]],
  ["Italiano", ["it-IT", "Italia"], ["it-CH", "Svizzera"]],
  ["ಕನ್ನಡ", ["kn-IN"]],
  ["ភាសាខ្មែរ", ["km-KH"]],
  ["Latviešu", ["lv-LV"]],
  ["Lietuvių", ["lt-LT"]],
  ["മലയാളം", ["ml-IN"]],
  ["मराठी", ["mr-IN"]],
  ["Magyar", ["hu-HU"]],
  ["ລາວ", ["lo-LA"]],
  ["Nederlands", ["nl-NL"]],
  ["नेपाली भाषा", ["ne-NP"]],
  ["Norsk bokmål", ["nb-NO"]],
  ["Polski", ["pl-PL"]],
  ["Português", ["pt-BR", "Brasil"], ["pt-PT", "Portugal"]],
  ["Română", ["ro-RO"]],
  ["සිංහල", ["si-LK"]],
  ["Slovenščina", ["sl-SI"]],
  ["Basa Sunda", ["su-ID"]],
  ["Slovenčina", ["sk-SK"]],
  ["Suomi", ["fi-FI"]],
  ["Svenska", ["sv-SE"]],
  ["Kiswahili", ["sw-TZ", "Tanzania"], ["sw-KE", "Kenya"]],
  ["ქართული", ["ka-GE"]],
  ["Հայերեն", ["hy-AM"]],
  [
    "தமிழ்",
    ["ta-IN", "இந்தியா"],
    ["ta-SG", "சிங்கப்பூர்"],
    ["ta-LK", "இலங்கை"],
    ["ta-MY", "மலேசியா"],
  ],
  ["తెలుగు", ["te-IN"]],
  ["Tiếng Việt", ["vi-VN"]],
  ["Türkçe", ["tr-TR"]],
  ["اُردُو", ["ur-PK", "پاکستان"], ["ur-IN", "بھارت"]],
  ["Ελληνικά", ["el-GR"]],
  ["български", ["bg-BG"]],
  ["Pусский", ["ru-RU"]],
  ["Српски", ["sr-RS"]],
  ["Українська", ["uk-UA"]],
  ["한국어", ["ko-KR"]],
  [
    "中文",
    ["cmn-Hans-CN", "普通话 (中国大陆)"],
    ["cmn-Hans-HK", "普通话 (香港)"],
    ["cmn-Hant-TW", "中文 (台灣)"],
    ["yue-Hant-HK", "粵語 (香港)"],
  ],
  ["日本語", ["ja-JP"]],
  ["हिन्दी", ["hi-IN"]],
  ["ภาษาไทย", ["th-TH"]],
];

export const langaugeOptions = [
  { label: "Afrikaans af-ZA", value: "af-ZA" },
  { label: "አማርኛ am-ET", value: "am-ET" },
  { label: "Azərbaycanca az-AZ", value: "az-AZ" },
  { label: "বাংলা bn-BD", value: "bn-BD" },
  { label: "বাংলা bn-IN", value: "bn-IN" },
  { label: "Bahasa Indonesia id-ID", value: "id-ID" },
  { label: "Bahasa Melayu ms-MY", value: "ms-MY" },
  { label: "Català ca-ES", value: "ca-ES" },
  { label: "Čeština cs-CZ", value: "cs-CZ" },
  { label: "Dansk da-DK", value: "da-DK" },
  { label: "Deutsch de-DE", value: "de-DE" },
  { label: "English en-AU", value: "en-AU" },
  { label: "English en-CA", value: "en-CA" },
  { label: "English en-IN", value: "en-IN" },
  { label: "English en-KE", value: "en-KE" },
  { label: "English en-TZ", value: "en-TZ" },
  { label: "English en-GH", value: "en-GH" },
  { label: "English en-NZ", value: "en-NZ" },
  { label: "English en-NG", value: "en-NG" },
  { label: "English en-ZA", value: "en-ZA" },
  { label: "English en-PH", value: "en-PH" },
  { label: "English en-GB", value: "en-GB" },
  { label: "English en-US", value: "en-US" },
  { label: "Español es-AR", value: "es-AR" },
  { label: "Español es-BO", value: "es-BO" },
  { label: "Español es-CL", value: "es-CL" },
  { label: "Español es-CO", value: "es-CO" },
  { label: "Español es-CR", value: "es-CR" },
  { label: "Español es-EC", value: "es-EC" },
  { label: "Español es-SV", value: "es-SV" },
  { label: "Español es-ES", value: "es-ES" },
  { label: "Español es-US", value: "es-US" },
  { label: "Español es-GT", value: "es-GT" },
  { label: "Español es-HN", value: "es-HN" },
  { label: "Español es-MX", value: "es-MX" },
  { label: "Español es-NI", value: "es-NI" },
  { label: "Español es-PA", value: "es-PA" },
  { label: "Español es-PY", value: "es-PY" },
  { label: "Español es-PE", value: "es-PE" },
  { label: "Español es-PR", value: "es-PR" },
  { label: "Español es-DO", value: "es-DO" },
  { label: "Español es-UY", value: "es-UY" },
  { label: "Español es-VE", value: "es-VE" },
  { label: "Euskara eu-ES", value: "eu-ES" },
  { label: "Filipino fil-PH", value: "fil-PH" },
  { label: "Français fr-FR", value: "fr-FR" },
  { label: "Basa Jawa jv-ID", value: "jv-ID" },
  { label: "Galego gl-ES", value: "gl-ES" },
  { label: "ગુજરાતી gu-IN", value: "gu-IN" },
  { label: "Hrvatski hr-HR", value: "hr-HR" },
  { label: "IsiZulu zu-ZA", value: "zu-ZA" },
  { label: "Íslenska is-IS", value: "is-IS" },
  { label: "Italiano it-IT", value: "it-IT" },
  { label: "Italiano it-CH", value: "it-CH" },
  { label: "ಕನ್ನಡ kn-IN", value: "kn-IN" },
  { label: "ភាសាខ្មែរ km-KH", value: "km-KH" },
  { label: "Latviešu lv-LV", value: "lv-LV" },
  { label: "Lietuvių lt-LT", value: "lt-LT" },
  { label: "മലയാളം ml-IN", value: "ml-IN" },
  { label: "मराठी mr-IN", value: "mr-IN" },
  { label: "Magyar hu-HU", value: "hu-HU" },
  { label: "ລາວ lo-LA", value: "lo-LA" },
  { label: "Nederlands nl-NL", value: "nl-NL" },
  { label: "नेपाली भाषा ne-NP", value: "ne-NP" },
  { label: "Norsk bokmål nb-NO", value: "nb-NO" },
  { label: "Polski pl-PL", value: "pl-PL" },
  { label: "Português pt-BR", value: "pt-BR" },
  { label: "Português pt-PT", value: "pt-PT" },
  { label: "Română ro-RO", value: "ro-RO" },
  { label: "සිංහල si-LK", value: "si-LK" },
  { label: "Slovenščina sl-SI", value: "sl-SI" },
  { label: "Basa Sunda su-ID", value: "su-ID" },
  { label: "Slovenčina sk-SK", value: "sk-SK" },
  { label: "Suomi fi-FI", value: "fi-FI" },
  { label: "Svenska sv-SE", value: "sv-SE" },
  { label: "Kiswahili sw-TZ", value: "sw-TZ" },
  { label: "Kiswahili sw-KE", value: "sw-KE" },
  { label: "ქართული ka-GE", value: "ka-GE" },
  { label: "Հայերեն hy-AM", value: "hy-AM" },
  { label: "தமிழ் ta-IN", value: "ta-IN" },
  { label: "தமிழ் ta-SG", value: "ta-SG" },
  { label: "தமிழ் ta-LK", value: "ta-LK" },
  { label: "தமிழ் ta-MY", value: "ta-MY" },
  { label: "తెలుగు te-IN", value: "te-IN" },
  { label: "Tiếng Việt vi-VN", value: "vi-VN" },
  { label: "Türkçe tr-TR", value: "tr-TR" },
  { label: "اُردُو ur-PK", value: "ur-PK" },
  { label: "اُردُو ur-IN", value: "ur-IN" },
  { label: "Ελληνικά el-GR", value: "el-GR" },
  { label: "български bg-BG", value: "bg-BG" },
  { label: "Pусский ru-RU", value: "ru-RU" },
  { label: "Српски sr-RS", value: "sr-RS" },
  { label: "Українська uk-UA", value: "uk-UA" },
  { label: "한국어 ko-KR", value: "ko-KR" },
  { label: "中文 cmn-Hans-CN", value: "cmn-Hans-CN" },
  { label: "中文 cmn-Hans-HK", value: "cmn-Hans-HK" },
  { label: "中文 cmn-Hant-TW", value: "cmn-Hant-TW" },
  { label: "中文 yue-Hant-HK", value: "yue-Hant-HK" },
  { label: "日本語 ja-JP", value: "ja-JP" },
  { label: "हिन्दी hi-IN", value: "hi-IN" },
  { label: "ภาษาไทย th-TH", value: "th-TH" },
];
